app: link-shortener
service: link-shortener

frameworkVersion: "2"

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs12.x
  stage: to
  apiGateway:
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  getLink:
    handler: handler.getLink
    events:
      - http:
          path: /{link}

  shortenLink:
    handler: handler.shortenLink
    events:
      - http:
          path: /
          method: post
          cors: true

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: shortname
            AttributeType: S
        KeySchema:
          - AttributeName: shortname
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: linkShortenerDB
