app: link-shorterner
service: link-shorterner

plugins:
  - serverless-api-gateway-caching

frameworkVersion: "2"

custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 3600

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true

functions:
  getLink:
    handler: handler.getLink
    events:
      - http:
          path: /{link}
          method: get
          caching:
            enabled: true
  shorternLink:
    handler: handler.shorternLink
    events:
      - http:
          path: /
          method: post
